#!/bin/bash
echo "=> Building the binary"
docker run --privileged \
  -v $(pwd):/usr/src/app  \
  -e "GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID" \
  -e "GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET" \
  starefossen/github-pages jekyll build

