markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
incremental: true
permalink: pretty
safe: false
lsi: false
exclude: [README.md]

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

sass:
  sass_dir:          _scss
  style:            :compressed

exclude: [node_modules, gulpfile.js]
